name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I click here this happens
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page X
        2. Click here
        3. Click there
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
  - type: input
    id: provider_used
    attributes:
      label: Which weather source are you using?
      placeholder: Provider name
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: checkboxes
    id: acknowledgementsCheck
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don’t read this carefully.
      options:
        - label: I have reviewed the existing issues to confirm that this is a unique report and not related to any currently open or closed tickets.
          required: true
        - label: I understand that this app is provided as-is, without any guarantees, and I might not receive a response to my request. Sometimes you might not get the response you want.
          required: true
