name: Add New Weather Provider
description: Request Weather Provider
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below
  - type: textarea
    id: description
    attributes:
      label: Name of the provider
      placeholder: Provider's website or API documentation link
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reason for Request
      placeholder: Why do you want this provider to be added?
                  (e.g., Better accuracy, additional features, regional coverage, etc.)
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Key Features or Benefits
      placeholder: List specific features of the provider that you think would improve the app.
                   (e.g., Hourly forecasts, radar data, historical weather, etc.)
  - type: checkboxes
    attributes:
      label: Provider's API Information
      description: Does the provider have a free API tier?
      options:
        - label: "Yes"
        - label: "No"
